name: Release Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Perform versioning if necessary
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: Bryan Larson
        GIT_AUTHOR_EMAIL: bryan_larson@hms.harvard.edu
      with:
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/changelog
          @semantic-release/git

    - name: Echo versioning
      run: |
        # Generate versions
        echo "New version released: '${{ steps.semantic.outputs.new_release_published }}'"
        echo "New version: '${{ steps.semantic.outputs.new_release_version }}'"
