name: Test Build Targets

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      targets:
        required: false
        default: "all"
        type: choice
        options:
          - "all"
          - "debian"
          - "debian slim"
          - "alpine"
          - "ubuntu"
        description: The target(s) to test build

jobs:
  matrices:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.generate-versions-matrices.outputs.python-versions }}
      debian-versions: ${{ steps.generate-versions-matrices.outputs.debian-versions }}
      alpine-versions: ${{ steps.generate-versions-matrices.outputs.alpine-versions }}
      ubuntu-versions: ${{ steps.generate-versions-matrices.outputs.ubuntu-versions }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate versions matrices
      id: generate-versions-matrices
      run: |
        # Generate versions
        echo "Python versions: $(python build.py versions python)"
        echo "echo "python-versions=$(python build.py versions python)" >> $GITHUB_OUTPUT"
        echo "Debian versions: $(python build.py versions debian)"
        echo "echo "debian-versions=$(python build.py versions debian)" >> $GITHUB_OUTPUT"
        echo "Alpine versions: $(python build.py versions alpine)"
        echo "echo "alpine-versions=$(python build.py versions alpine)" >> $GITHUB_OUTPUT"
        echo "Ubuntu versions: $(python build.py versions ubuntu)"
        echo "echo "ubuntu-versions=$(python build.py versions ubuntu)" >> $GITHUB_OUTPUT"

  version:
    runs-on: ubuntu-latest
    outputs:
      dbmisvc-docker-version: ${{ steps.get-version-tag.outputs.tag }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Get Latest Tag
      id: get-version-tag
      uses: WyriHaximus/github-action-get-previous-tag@v1

  build-debian:
    if: github.event_name == 'pull_request' || github.event.inputs.targets == 'all' || github.event.inputs.targets == 'debian'
    needs:
      - matrices
      - version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.matrices.outputs.python-versions) }}
        os-version: ${{ fromJson(needs.matrices.outputs.debian-versions) }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - id: build-debian-targets
      name: Build Debian targets
      uses: ./.github/actions/build-target
      with:
        target: "debian"
        os-version: "${{ matrix.os-version }}"
        python-version: "${{ matrix.python-version }}"
        repo: "${{ secrets.DBMISVC_REPO }}"
        version: "${{ needs.version.outputs.dbmisvc-docker-version }}"
        docker-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        docker-password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

  build-debian-slim:
    if: github.event_name == 'pull_request' || github.event.inputs.targets == 'all' || github.event.inputs.targets == 'debian-slim'
    needs:
      - matrices
      - version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.matrices.outputs.python-versions) }}
        os-version: ${{ fromJson(needs.matrices.outputs.debian-versions) }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - id: build-debian-slim-targets
      name: Build Debian Slim targets
      uses: ./.github/actions/build-target
      with:
        target: "debian-slim"
        os-version: "${{ matrix.os-version }}"
        python-version: "${{ matrix.python-version }}"
        repo: "${{ secrets.DBMISVC_REPO }}"
        version: "${{ needs.version.outputs.dbmisvc-docker-version }}"
        docker-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        docker-password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

  build-alpine:
    if: github.event_name == 'pull_request' || github.event.inputs.targets == 'all' || github.event.inputs.targets == 'alpine'
    needs:
      - matrices
      - version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.matrices.outputs.python-versions) }}
        os-version: ${{ fromJson(needs.matrices.outputs.alpine-versions) }}
        exclude:
          - os-version: "3.12"
            python-version: "3.11"
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - id: build-alpine-targets
      name: Build Alpine targets
      uses: ./.github/actions/build-target
      with:
        target: "alpine"
        os-version: "${{ matrix.os-version }}"
        python-version: "${{ matrix.python-version }}"
        repo: "${{ secrets.DBMISVC_REPO }}"
        version: "${{ needs.version.outputs.dbmisvc-docker-version }}"
        docker-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        docker-password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

  build-ubuntu:
    if: github.event_name == 'pull_request' || github.event.inputs.targets == 'all' || github.event.inputs.targets == 'ubuntu'
    needs:
      - matrices
      - version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.matrices.outputs.python-versions) }}
        os-version: ${{ fromJson(needs.matrices.outputs.ubuntu-versions) }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - id: build-ubuntu-targets
      name: Build Ubuntu targets
      uses: ./.github/actions/build-target
      with:
        target: "ubuntu"
        os-version: "${{ matrix.os-version }}"
        python-version: "${{ matrix.python-version }}"
        repo: "${{ secrets.DBMISVC_REPO }}"
        version: "${{ needs.version.outputs.dbmisvc-docker-version }}"
        docker-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        docker-password: "${{ secrets.DOCKER_HUB_PASSWORD }}"
